### ISSUE TITLE
Only first 65 397 bytes get uploaded

### ISSUE THREAD

**Issue by robertrossmann** [lukasreichart/skipper-azure#1]
Hi! I am trying to upload an `image/jpeg` file into my Azure container. My file is 286 025 bytes large, but only first 65 397 bytes get uploaded - after that, the adapter fires my callback and reports a successful operation.

Interesting to note is that the uploaded file is consistently truncated to 65 397 bytes even after multiple attempts.

Here is a short code that I use:

``` js
return new Promise(function upload (resolve, reject) {
  // Upload! blobStore contains skipper-azure as adapter and all necessary keys and secrets
  req.file('photo').upload(sails.config.connections.blobStore, function (err, files) {
    // Error occured?
    if (err)
      return reject(err)

    // Did we upload anything?
    if (! files.length)
      err = new Error('No files uploaded!')

    return resolve(files[0])    // We only upload one at a time
  })
})
```

And I upload my file with `curl`:

`curl -X POST -F "photo=@/path/to/test.jpg" http://localhost:000/contacts/1/photo`

After that, Sails sends me the expected response and closes the connection normally. Could this be a bug in the module...?

Thanks for any guidance in this matter!

**Comment by lukasredev** [comment]
Fixed in the newest commit. I'll also update the npm version soon.
